// <auto-generated />
using KitchenAid;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenAid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110212429_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("KitchenAid.Table.Allergies", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("KitchenAid.Table.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("KitchenAid.Table.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Oil"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Parmesan"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Anchovy"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Mayonnaise"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Salad Leaf"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Crouton"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Caesar Dressing"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Caesar Salad"
                        });
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient");
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeSubRecipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChildRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ParentRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildRecipeId");

                    b.HasIndex("ParentRecipeId");

                    b.ToTable("SubRecipes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChildRecipeId = 1L,
                            ParentRecipeId = 8L
                        },
                        new
                        {
                            Id = 2L,
                            ChildRecipeId = 3L,
                            ParentRecipeId = 8L
                        },
                        new
                        {
                            Id = 3L,
                            ChildRecipeId = 2L,
                            ParentRecipeId = 8L
                        },
                        new
                        {
                            Id = 4L,
                            ChildRecipeId = 3L,
                            ParentRecipeId = 9L
                        },
                        new
                        {
                            Id = 5L,
                            ChildRecipeId = 4L,
                            ParentRecipeId = 9L
                        },
                        new
                        {
                            Id = 6L,
                            ChildRecipeId = 5L,
                            ParentRecipeId = 9L
                        },
                        new
                        {
                            Id = 7L,
                            ChildRecipeId = 6L,
                            ParentRecipeId = 9L
                        },
                        new
                        {
                            Id = 8L,
                            ChildRecipeId = 7L,
                            ParentRecipeId = 10L
                        },
                        new
                        {
                            Id = 9L,
                            ChildRecipeId = 8L,
                            ParentRecipeId = 10L
                        },
                        new
                        {
                            Id = 10L,
                            ChildRecipeId = 9L,
                            ParentRecipeId = 10L
                        });
                });

            modelBuilder.Entity("KitchenAid.Table.Allergies", b =>
                {
                    b.HasOne("KitchenAid.Table.Ingredient", null)
                        .WithMany("AllergieIds")
                        .HasForeignKey("IngredientId");
                });

            modelBuilder.Entity("KitchenAid.Table.Recipe", b =>
                {
                    b.OwnsOne("KitchenAid.Table.UnitAndMeasure", "FinalMeasure", b1 =>
                        {
                            b1.Property<long>("RecipeId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Measurement")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Unit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.HasData(
                                new
                                {
                                    RecipeId = 1L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 2L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 3L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 4L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 5L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 6L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 7L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 8L,
                                    Measurement = 100m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeId = 9L,
                                    Measurement = 300m,
                                    Unit = 1
                                },
                                new
                                {
                                    RecipeId = 10L,
                                    Measurement = 250m,
                                    Unit = 0
                                });
                        });

                    b.Navigation("FinalMeasure");
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeIngredient", b =>
                {
                    b.HasOne("KitchenAid.Table.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAid.Table.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KitchenAid.Table.UnitAndMeasure", "UnitsAndMeasures", b1 =>
                        {
                            b1.Property<long>("RecipeIngredientId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Measurement")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Unit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecipeIngredientId");

                            b1.ToTable("RecipeIngredient");

                            b1.WithOwner()
                                .HasForeignKey("RecipeIngredientId");
                        });

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitsAndMeasures")
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeSubRecipe", b =>
                {
                    b.HasOne("KitchenAid.Table.Recipe", "ChildRecipe")
                        .WithMany()
                        .HasForeignKey("ChildRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAid.Table.Recipe", "ParentRecipe")
                        .WithMany("SubRecipes")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KitchenAid.Table.UnitAndMeasure", "UnitsAndMeasures", b1 =>
                        {
                            b1.Property<long>("RecipeSubRecipeId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Measurement")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Unit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecipeSubRecipeId");

                            b1.ToTable("SubRecipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeSubRecipeId");

                            b1.HasData(
                                new
                                {
                                    RecipeSubRecipeId = 1L,
                                    Measurement = 90m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 2L,
                                    Measurement = 4m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 3L,
                                    Measurement = 30m,
                                    Unit = 1
                                },
                                new
                                {
                                    RecipeSubRecipeId = 4L,
                                    Measurement = 8m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 5L,
                                    Measurement = 60m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 6L,
                                    Measurement = 10m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 7L,
                                    Measurement = 280m,
                                    Unit = 1
                                },
                                new
                                {
                                    RecipeSubRecipeId = 8L,
                                    Measurement = 150m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 9L,
                                    Measurement = 30m,
                                    Unit = 0
                                },
                                new
                                {
                                    RecipeSubRecipeId = 10L,
                                    Measurement = 70m,
                                    Unit = 1
                                });
                        });

                    b.Navigation("ChildRecipe");

                    b.Navigation("ParentRecipe");

                    b.Navigation("UnitsAndMeasures")
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenAid.Table.Ingredient", b =>
                {
                    b.Navigation("AllergieIds");
                });

            modelBuilder.Entity("KitchenAid.Table.Recipe", b =>
                {
                    b.Navigation("SubRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
