// <auto-generated />
using KitchenAid;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenAid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107133822_AddIngredientRecord")]
    partial class AddIngredientRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("KitchenAid.Table.Allergies", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("KitchenAid.Table.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("KitchenAid.Table.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient");
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeSubRecipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChildRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ParentRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildRecipeId");

                    b.HasIndex("ParentRecipeId");

                    b.ToTable("RecipeSubRecipe");
                });

            modelBuilder.Entity("KitchenAid.Table.Allergies", b =>
                {
                    b.HasOne("KitchenAid.Table.Ingredient", null)
                        .WithMany("AllergieIds")
                        .HasForeignKey("IngredientId");
                });

            modelBuilder.Entity("KitchenAid.Table.Recipe", b =>
                {
                    b.OwnsOne("KitchenAid.Table.UnitAndMeasure", "FinalMeasure", b1 =>
                        {
                            b1.Property<long>("RecipeId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Measurement")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Unit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("FinalMeasure");
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeIngredient", b =>
                {
                    b.HasOne("KitchenAid.Table.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAid.Table.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KitchenAid.Table.UnitAndMeasure", "UnitsAndMeasures", b1 =>
                        {
                            b1.Property<long>("RecipeIngredientId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Measurement")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Unit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecipeIngredientId");

                            b1.ToTable("RecipeIngredient");

                            b1.WithOwner()
                                .HasForeignKey("RecipeIngredientId");
                        });

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitsAndMeasures")
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenAid.Table.RecipeSubRecipe", b =>
                {
                    b.HasOne("KitchenAid.Table.Recipe", "ChildRecipe")
                        .WithMany()
                        .HasForeignKey("ChildRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAid.Table.Recipe", "ParentRecipe")
                        .WithMany()
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KitchenAid.Table.UnitAndMeasure", "UnitsAndMeasures", b1 =>
                        {
                            b1.Property<long>("RecipeSubRecipeId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Measurement")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Unit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecipeSubRecipeId");

                            b1.ToTable("RecipeSubRecipe");

                            b1.WithOwner()
                                .HasForeignKey("RecipeSubRecipeId");
                        });

                    b.Navigation("ChildRecipe");

                    b.Navigation("ParentRecipe");

                    b.Navigation("UnitsAndMeasures")
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenAid.Table.Ingredient", b =>
                {
                    b.Navigation("AllergieIds");
                });

            modelBuilder.Entity("KitchenAid.Table.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
